### PR TITLE
Tweak for v0.14 Compatible layer

### PR DESCRIPTION
**Pull request by cosmo0920**
These patches are needed to work with Fluentd v0.14's compatible layer for traditional plugins.
Could you check it?

### CODE REVIEW

**Comment by v9n** [comment]
@cosmo0920 Hi, thanks for this. I'm merging now.

**Comment by v9n** [comment]
@cosmo0920 Would you like to become a collbator on this as well?

**Comment by cosmo0920** [comment]
I'd appreciate your suggestion.
If you were OK,  I'd like to maintain this plugin in @fluent-plugins-nursery.
This organization is aimed for collaborating to maintain Fluentd plugins which are not actively well maintained plugins for now.

But I'm acceptable to become a collaborator on this.
I respect your decision.

**Comment by v9n** [comment]
@cosmo0920 yes. we can move this to https://github.com/fluent-plugins-nursery. let me know how to proceed

**Comment by cosmo0920** [comment]
@v9n Could you follow the moving process here? https://github.com/fluent-plugins-nursery/contact

**Comment by v9n** [comment]
Hi @cosmo0920 Sorry for years in delay. I tried to initiated the moving but got

Screenshot 2022-11-27 at 4 22 06 PM

Any idea how to proceed? My email is vinh@mailwip.com you can email me directly if I don't respond. thanks so much.

**Pull request merged**
